#!/usr/bin/env python3
"""Derive the standalone Unity package from the checked-in upstream bindings.

Run after the CppSharp generator. No native binaries or third-party Python modules
are needed. --check is suitable for CI and never writes files.
"""

import argparse
from pathlib import Path
import re
import sys
import uuid

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "Unity"
SOURCE = ROOT / "FFmpeg.AutoGen"
HEADER = "// <auto-generated>Generated by Tools/generate-unity.py. Do not edit.</auto-generated>\n"
WINDOWS = "UNITY_EDITOR_WIN || (UNITY_STANDALONE_WIN && !UNITY_EDITOR)"
MAC = "UNITY_EDITOR_OSX || (UNITY_STANDALONE_OSX && !UNITY_EDITOR)"
LINUX = "UNITY_EDITOR_LINUX || (UNITY_STANDALONE_LINUX && !UNITY_EDITOR)"
LONG_ALIASES = f"""#if {WINDOWS}
using CLong = System.Int32;
using CULong = System.UInt32;
#else
using CLong = System.Int64;
using CULong = System.UInt64;
#endif"""


def block_namespace(text):
    text, count = re.subn(r"^namespace FFmpeg\.AutoGen;", "namespace FFmpeg.AutoGen\n{", text, flags=re.M)
    if count != 1:
        raise ValueError("Expected exactly one file-scoped namespace")
    return HEADER + text.rstrip() + "\n}\n"


def read_source(name):
    return (SOURCE / name).read_text(encoding="utf-8-sig")


def plain_parameters(parameters):
    result = []
    if not parameters.strip():
        return result
    for parameter in parameters.split(","):
        match = re.fullmatch(r"\s*(?:(in|ref) )?([\w*\[\]]+) (@\w+)\s*", parameter)
        if not match:
            raise ValueError(f"Unrecognized parameter: {parameter}")
        modifier, kind, name = match.groups()
        result.append((modifier, kind, name))
    return result


def generate_function(match, libraries):
    returns, name, parameters = match.groups()
    library = libraries[name]
    arguments = plain_parameters(parameters)
    native_parameters, calls, scopes = [], [], []
    has_strings = returns == "string" or any(kind == "string" for _, kind, _ in arguments)
    raw_return = "byte*" if returns == "string" else returns
    for modifier, kind, arg in arguments:
        local = "__" + arg[1:]
        if kind == "string":
            native_parameters.append(f"byte* {arg}")
            scopes.append(f"using (var {local} = new Utf8String({arg}))")
            calls.append(local + ".Pointer")
        elif kind.endswith("[]"):
            raw = kind[:-2] + "*"
            native_parameters.append(f"{raw} {arg}")
            scopes.append(f"fixed ({raw} {local} = {arg})")
            calls.append(local)
        elif modifier:
            native_parameters.append(f"{kind}* {arg}")
            scopes.append(f"fixed ({kind}* {local} = &{arg})")
            calls.append(local)
        elif kind.endswith("_func"):
            native_parameters.append(f"IntPtr {arg}")
            calls.append(arg + ".Pointer")
        else:
            native_parameters.append(f"{kind} {arg}")
            calls.append(arg)
    attribute = f'[DllImport(NativeLibraries.{library}, EntryPoint = "{name}", ExactSpelling = true, CallingConvention = CallingConvention.Cdecl)]'
    converted = has_strings or bool(scopes) or any(kind.endswith("_func") for _, kind, _ in arguments)
    if not converted:
        return f"    {attribute}\n    public static extern {returns} {name}({parameters});"

    raw_parameters = ", ".join(native_parameters)
    invocation = f"__PInvoke_{name}({', '.join(calls)})"
    if returns == "string":
        invocation = f"Utf8String.Read({invocation})"
    statement = ("" if returns == "void" else "return ") + invocation + ";"
    lines = [f"    public static {returns} {name}({parameters})", "    {"]
    # HGlobal buffers belong to the managed call. FFmpeg must never take ownership
    # of them (and its allocator need not match Marshal.FreeHGlobal on Windows).
    ownership = {"av_dict_set": "AV_DICT_DONT_STRDUP_KEY | AV_DICT_DONT_STRDUP_VAL", "av_dict_set_int": "AV_DICT_DONT_STRDUP_KEY"}
    if name in ownership:
        lines += [f"        if ((@flags & ({ownership[name]})) != 0)",
                  f'            throw new ArgumentException("String arguments cannot transfer ownership. Use {name}_utf8 with FFmpeg-allocated pointers.", nameof(@flags));']
    lines += ["        " + scope for scope in scopes]
    lines += (["        {", "            " + statement, "        }"] if scopes else ["        " + statement])
    lines += ["    }", "", "    " + attribute,
              f"    private static extern {raw_return} __PInvoke_{name}({raw_parameters});"]
    if has_strings:
        # Separate names avoid making existing calls with null string arguments ambiguous.
        lines += ["", "    /// <summary>Raw UTF-8 pointer form. Follow the native API's buffer lifetime and ownership rules.</summary>",
                  f"    public static {raw_return} {name}_utf8({raw_parameters}) => __PInvoke_{name}({', '.join(arg for _, _, arg in arguments)});"]
    return "\n".join(lines)


def generated_files():
    files = {}
    generated = PACKAGE / "Runtime" / "Generated"
    for name in ["Arrays.g.cs", "Enums.g.cs", "Structs.g.cs", "Delegates.g.cs", "ffmpeg.macros.g.cs", "ffmpeg.functions.inline.g.cs", "ffmpeg.libraries.g.cs"]:
        text = read_source("generated/" + name)
        text = re.sub(r"#if NET6_0_OR_GREATER\nusing CLong = .*?\n#endif", LONG_ALIASES, text, flags=re.S)
        if name == "Structs.g.cs":
            # Windows SDK DWORD/ULONG members are always 32-bit, even when these
            # otherwise-unused hardware structures are compiled on a Unix host.
            for field in ["Data1", "surface_type"]:
                old = f"public CULong @{field};"
                if text.count(old) != 1:
                    raise ValueError(f"Expected one Windows ULONG field: {field}")
                text = text.replace(old, f"public uint @{field};")
        if name == "Delegates.g.cs":
            text = re.sub(r"#if NETSTANDARD2_1_OR_GREATER \|\| NET\s*\[MarshalAs\(UnmanagedType.LPUTF8Str\)\]\s*#else\s*\[MarshalAs\(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof\(UTF8Marshaler\)\)\]\s*#endif\s*string", "byte*", text)
            # Reverse P/Invoke signatures must contain native pointers, not
            # marshaled managed strings or single-field callback structs.
            text = re.sub(r"(public unsafe delegate[^;]+);", lambda m: re.sub(r"\b\w+_func (?=@)", "IntPtr ", m[0]), text)
            if "MarshalAs" in text:
                raise ValueError("New callback marshalling requires review")
        files[generated / name] = block_namespace(text)

    linked = (ROOT / "FFmpeg.AutoGen.Bindings.DynamicallyLinked/generated/DynamicallyLinkedBindings.g.cs").read_text(encoding="utf-8-sig")
    imports = re.findall(r'\[DllImport\("(\w+)-(\d+)", CallingConvention = CallingConvention.Cdecl\)\][\s\S]*?public static extern \S+ (\w+)\(', linked)
    libraries = {name: library for library, _, name in imports}
    versions = dict((library, version) for library, version, _ in imports)
    facade = read_source("generated/ffmpeg.functions.facade.g.cs")
    pattern = r"^    public static (\S+) (\w+)\(([^\n]*)\) => vectors\.[^\n]+;"
    facade, count = re.subn(pattern, lambda m: generate_function(m, libraries), facade, flags=re.M)
    if count != len(libraries) or "vectors." in facade:
        raise ValueError(f"Facade/import mismatch: {count} functions, {len(libraries)} imports")
    files[generated / "ffmpeg.functions.g.cs"] = block_namespace(facade)
    constants = [HEADER.rstrip(), "namespace FFmpeg.AutoGen", "{", "internal static class NativeLibraries", "{"]
    for condition, template in [(WINDOWS, "{lib}-{version}"), (MAC, "lib{lib}.{version}.dylib"), (LINUX, "lib{lib}.so.{version}"), ("UNITY_ANDROID && !UNITY_EDITOR", "{lib}"), ("UNITY_IOS && !UNITY_EDITOR", "__Internal")]:
        constants.append(("#if " if condition == WINDOWS else "#elif ") + condition)
        for lib, version in sorted(versions.items()):
            constants.append(f'    internal const string {lib} = "{template.format(lib=lib, version=version)}";')
    constants += ["#else", '#error FFmpeg.AutoGen supports only 64-bit Windows, Linux, macOS, Android and iOS.', "#endif", "}", "}", ""]
    files[generated / "NativeLibraries.g.cs"] = "\n".join(constants)
    files[generated / "IFixedArray.g.cs"] = block_namespace(read_source("IFixedArray.cs"))
    files[PACKAGE / "LICENSE.md"] = (ROOT / "LICENSE.txt").read_text(encoding="utf-8-sig")
    return files, count


def metadata(path, is_folder):
    key = "FFmpeg.AutoGen/Unity/" + path.relative_to(PACKAGE).as_posix()
    guid = uuid.uuid5(uuid.NAMESPACE_URL, key).hex
    result = f"fileFormatVersion: 2\nguid: {guid}\n"
    if is_folder:
        result += "folderAsset: yes\n"
    importer = "MonoImporter" if path.suffix == ".cs" else "AssemblyDefinitionImporter" if path.suffix == ".asmdef" else "DefaultImporter"
    result += f"{importer}:\n"
    if importer == "MonoImporter":
        result += "  externalObjects: {}\n  serializedVersion: 2\n  defaultReferences: []\n  executionOrder: 0\n  icon: {instanceID: 0}\n"
    result += "  userData: \n  assetBundleName: \n  assetBundleVariant: \n"
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files, count = generated_files()
    # Stable GUIDs prevent reimports and broken asmdef references after submodule updates.
    paths = set(PACKAGE.rglob("*")) | set(files)
    for path in list(paths):
        paths.update(p for p in path.parents if p != PACKAGE and PACKAGE in p.parents)
    for path in sorted(paths):
        if path.suffix == ".meta" or any(part.endswith("~") or part.startswith(".") for part in path.relative_to(PACKAGE).parts):
            continue
        files[Path(str(path) + ".meta")] = metadata(path, path not in files and (path.is_dir() or any(path in f.parents for f in files)))
    changed = []
    for path, contents in sorted(files.items()):
        if path.exists() and path.read_text(encoding="utf-8") == contents:
            continue
        changed.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents, encoding="utf-8", newline="\n")
    if args.check and changed:
        print("Unity package needs regeneration:\n" + "\n".join(changed), file=sys.stderr)
        return 1
    print(f"Unity bindings: {count} native functions; {len(changed)} {'stale' if args.check else 'updated'} files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
